// Generated by Wrangler by running `wrangler types`

interface Env {
	PROCESSED_POSTS_KV: KVNamespace;
	GOOGLE_GEMINI_API_KEY: string;
	TELEGRAM_CHAT_ID: string;
	TELEGRAM_BOT_TOKEN: string;
	BROWSER: Fetcher;
}
